import * as fs from "fs";
import * as path from "path";

/**
 * `arol-ai init` — wire the scan into a repo's CI with one command.
 *
 * Scope is deliberately narrow: we generate a GitHub Actions workflow file and
 * nothing else. No package.json edits (a scanner does not belong in the local
 * build loop — a sunset entering the failure window would break `npm run build`
 * on laptops with zero code changes), no secret handling, no network. The dev
 * reviews the generated file in their diff like any other change.
 */

/** Path of the workflow we generate, relative to the repo root. */
export const WORKFLOW_PATH = path.join(".github", "workflows", "arol.yml");

/**
 * The canonical CI recipe — this template is the single source of truth
 * (docs/ci.md describes it in prose rather than duplicating it).
 *
 * Triggers, and why:
 * - pull_request + push to main/master: gate merges without double-running on
 *   feature-branch pushes.
 * - weekly schedule: the differentiating one. Deprecations land on repos with
 *   NO code changes; a failed scheduled run (GitHub emails those) is the early
 *   warning even when nobody pushes. Off-hour minute per GitHub's guidance.
 * - workflow_dispatch: manual re-run after fixing findings.
 *
 * The AROL_REPORT_TOKEN env line is safe without the secret: GitHub renders a
 * missing secret as an empty string, and an empty token means the CLI never
 * uploads anything (reporting is strictly opt-in).
 */
export function workflowYaml(): string {
  return `# Arol — catches deprecated third-party APIs, SDKs, and model ids in this
# repo before their sunset dates break it. Generated by \`arol-ai init\`.
# Tuning and docs: https://github.com/benminor/arol/blob/main/docs/ci.md
name: arol deprecation scan

on:
  pull_request:
  push:
    branches: [main, master]
  schedule:
    # Weekly — deprecations land even when nobody pushes. A failed scheduled
    # run is your early warning that a sunset date got close.
    - cron: "17 9 * * 1"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Exits 1 only on actionable findings: high severity, or a sunset
      # within 30 days (tune with --within <days>).
      - run: npx arol-ai scan
        env:
          # Optional — continuous monitoring. Create a token at
          # https://arol.ai/dashboard/tokens and add it as a repo secret named
          # AROL_REPORT_TOKEN. Left unset, nothing is ever uploaded.
          AROL_REPORT_TOKEN: \${{ secrets.AROL_REPORT_TOKEN }}
`;
}

export type InitOutcome =
  /** Workflow written (or overwritten with --force). */
  | { kind: "written"; file: string }
  /** An arol workflow already exists. `ours` = it is exactly our arol.yml. */
  | { kind: "already"; file: string; ours: boolean }
  /** Not inside a git repository. */
  | { kind: "not-git" }
  /** Every git remote points somewhere that clearly isn't GitHub. */
  | { kind: "non-github"; host: string };

/** Walk upward from `start` until a directory containing `.git` is found. */
export function findRepoRoot(start: string): string | null {
  let dir = path.resolve(start);
  // Bounded walk: path.dirname of a filesystem root returns itself.
  for (;;) {
    if (fs.existsSync(path.join(dir, ".git"))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/** Hostname from a git remote url — handles https://, ssh://, and scp-like git@host:path. */
function hostOf(url: string): string | null {
  const scp = /^[^@\s]+@([^:/\s]+)[:/]/.exec(url);
  if (scp) return scp[1].toLowerCase();
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    return null;
  }
}

/**
 * Remote hostnames from .git/config. Empty when there are no remotes yet, when
 * `.git` is a worktree/submodule pointer file, or when parsing fails — all of
 * which we treat permissively (a GitHub workflow file is inert elsewhere).
 */
export function remoteHosts(repoRoot: string): string[] {
  try {
    const gitPath = path.join(repoRoot, ".git");
    if (!fs.statSync(gitPath).isDirectory()) return [];
    const config = fs.readFileSync(path.join(gitPath, "config"), "utf8");
    const hosts: string[] = [];
    for (const m of config.matchAll(/^\s*url\s*=\s*(.+?)\s*$/gm)) {
      const host = hostOf(m[1]);
      if (host) hosts.push(host);
    }
    return hosts;
  } catch {
    return [];
  }
}

/**
 * Find any existing workflow that already runs arol. Checks our arol.yml by
 * name first, then the content of every other workflow file — someone who
 * hand-wrote the docs recipe under ci.yml should not get a duplicate.
 * Returns the path relative to the repo root, or null.
 */
export function findExistingArolWorkflow(repoRoot: string): string | null {
  const oursAbs = path.join(repoRoot, WORKFLOW_PATH);
  if (fs.existsSync(oursAbs)) return WORKFLOW_PATH;

  const dir = path.join(repoRoot, ".github", "workflows");
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    return null;
  }
  for (const name of entries) {
    if (!/\.ya?ml$/i.test(name)) continue;
    try {
      const body = fs.readFileSync(path.join(dir, name), "utf8");
      if (body.includes("arol-ai")) {
        return path.join(".github", "workflows", name);
      }
    } catch {
      // Unreadable workflow file — not ours to judge; keep looking.
    }
  }
  return null;
}

/**
 * The init operation, side effects and all, decoupled from printing so tests
 * can assert on outcomes. `cwd` may be anywhere inside the repo — the workflow
 * is written at the repo root, where GitHub looks for it.
 */
export function runInit(cwd: string, opts: { force?: boolean } = {}): InitOutcome {
  const repoRoot = findRepoRoot(cwd);
  if (!repoRoot) return { kind: "not-git" };

  const hosts = remoteHosts(repoRoot);
  if (hosts.length > 0 && !hosts.some((h) => h.includes("github"))) {
    return { kind: "non-github", host: hosts[0] };
  }

  if (!opts.force) {
    const existing = findExistingArolWorkflow(repoRoot);
    if (existing) {
      return { kind: "already", file: existing, ours: existing === WORKFLOW_PATH };
    }
  }

  const abs = path.join(repoRoot, WORKFLOW_PATH);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, workflowYaml(), "utf8");
  return { kind: "written", file: WORKFLOW_PATH };
}

/**
 * Should the scan report end with the "add this to CI" hint? Yes only when it
 * could land: interactive use (not already in CI), inside a git repo, and no
 * arol workflow present yet. The findings-count condition lives at the render
 * site, which already has the findings.
 */
export function shouldSuggestInit(
  scanRoot: string,
  env: NodeJS.ProcessEnv = process.env
): boolean {
  if (env.CI) return false;
  const repoRoot = findRepoRoot(scanRoot);
  if (!repoRoot) return false;
  return findExistingArolWorkflow(repoRoot) === null;
}
